### PR TITLE
Switch to using `npx` for serverless deploys

### PR DESCRIPTION
**Pull request by hockeybuggy**
When we used the `serverless-node-template` to create this repository
the existing serverless deploy "stuff" in the GitHub action workflow
file didn't work.

To resolve this we reached for a GitHub action "package" here:
https://github.com/GoProperly/properly-air-call-integration/commit/8ccbe3f525e7dc95d5a596a7e9deabb2a96aa933#diff-fac03d376dffe874b7262e22d79c5108

Gavin has a preference to use this approach and changed to template to use `npx`:
https://github.com/GoProperly/serverless-node-template/pull/497/files.
His preference is based on being able to control which version of
`serverless` is installed (expressed here:
#2 (comment))

This commit switches to using the same approach as the template for the
sake of consistency. This option was chosen over changing the template
because:
- The ability to control the version of `serverless` used.
- This repository already has `serverless` installed, which was not
  being used when using the GitHub actions approach.

### CODE REVIEW

**Comment by hockeybuggy** [comment]
@gavinsharp Ah pardon me. I missed this comment: https://github.com/GoProperly/properly-air-call-integration/pull/2#issuecomment-675155725

Makes sense.

**Comment by hockeybuggy** [comment]
Commit message and PR description updated to incorporate the reasons why Gavin prefers the `npx` approach.

**Comment by gavinsharp** [comment]
I just thought of another benefit of this approach: the [`serverless/github-action`](https://github.com/serverless/github-action) action requires spin-up of a Docker container and [separate `npm install`ation of `serverless`](https://github.com/serverless/github-action/blob/e17abe72d4969e86cb53576ade34e95c40362f0e/Dockerfile#L14), which is  less efficient than using the `serverless` that is already installed by our [CI "install" step](https://github.com/GoProperly/properly-air-call-integration/blob/bb1b4cdc253119818616c0d36ddfe4609833cdd5/.github/workflows/test_and_deploy.yml#L29), and [cached across builds](https://github.com/GoProperly/properly-air-call-integration/blob/bb1b4cdc253119818616c0d36ddfe4609833cdd5/.github/workflows/test_and_deploy.yml#L14-L19).

That lets us skip the "Build serverless/github-action@master" step which actually seems to take a non-trivial 52 seconds in this run from before this change: https://github.com/GoProperly/properly-air-call-integration/runs/998768179?check_suite_focus=true#step:2:1

**Comment by hockeybuggy** [comment]
Nice! Good point. :metal:

**Pull request merged**
