### PR TITLE
Uncomment the "deploy bypasses"

### PR DESCRIPTION
**Pull request by hockeybuggy**
The template comments out the lines that would deploy things to prod and
staging. This commit adds those back in which should cause these to be
deployed.

### CODE REVIEW

**Comment by gavinsharp** [comment]
FWIW: the model we've used elsewhere it to `npm install` `serverless` directly (i.e. commit the relevant `package.json`/`package-lock.json` changes), so that the version of `serverless` we end up using for the deploy is managed by us (vs. managed by `serverless/github-action`). But it probably doesn't matter much in practice (`serverless` tends to maintain backwards compatibility and not break often).

**Comment by gavinsharp** [comment]
Oh, I see now that it is installed: https://github.com/GoProperly/properly-air-call-integration/blob/568621252cf6c05dc0ba65cbf59dd1c7db0d84e6/package.json#L41.

Not sure why your first change didn't work then. Weird. Maybe something changed in GitHub Actions since the template was set up?

**Comment by hockeybuggy** [comment]
> Not sure why your first change didn't work then. Weird. Maybe something changed in GitHub Actions since the template was set up?

I don't think this template worked with serverless after moving to GitHub actions. We seem to use Travis for deploying the offer portal still and the template has the serverless calls commented out.

**Comment by gavinsharp** [comment]
> I don't think this template worked with serverless after moving to GitHub actions. We seem to use Travis for deploying the offer portal still and the template has the serverless calls commented out.

I think you're right! I think using `npx serverless` in the `deploy` alias would fix it, though I don't really want to deploy the template just to test it 😄

**Comment by hockeybuggy** [comment]
>  I think using npx serverless in the deploy alias would fix it, though I don't really want to deploy the template just to test it

Sure. Is there an issue using the action?

**Comment by gavinsharp** [comment]
> Sure. Is there an issue using the action?

Sorry I am just thinking out loud, not suggesting there's a problem to be fixed. No downside to using the action (other than aforementioned "no control over version of serverless used", which I don't think matters).

**Comment by gavinsharp** [comment]
Though I guess we should fix the template for future users to avoid them running into this. I can followup.

**Pull request merged**
